export const TrendingRestaurent = [
  {
    restaurant_id: "73",
    rest_name: "Ibaco",
    res_description: "Tasty and Delicious Ice Creams",
    min_order_value: "0",
    delivery_handled_by: "2",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "0",
    close_time: "22:50",
    open_time: "10:30",
    break_start_time: "18:00",
    break_end_time: "18:30",
    latitude: "12.9653847",
    longitude: "80.246198",
    del_prep_time: "0hr 35min",
    offline_status: [],
    isWishList: "1",
    distance: 1124,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "81",
    rest_name: "lassi corner",
    res_description: "Sweet lasi available here with quality",
    min_order_value: "0",
    delivery_handled_by: "2",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "0",
    close_time: "23:30",
    open_time: "10:30",
    break_start_time: "13:30",
    break_end_time: "14:30",
    latitude: "12.9653847",
    longitude: "80.246198",
    del_prep_time: "0hr 45min",
    offline_status: [],
    isWishList: "0",
    distance: 1124,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "4",
    rest_name: "Paradise Biryani",
    res_description: "Kerala, Indian Restaurant",
    min_order_value: "25",
    delivery_handled_by: "2",
    time_mode: "2",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "3.9",
    close_time: "",
    open_time: "",
    break_start_time: "",
    break_end_time: "",
    latitude: "1.4269313",
    longitude: "103.8260922",
    del_prep_time: "1hr 15min",
    offline_status: {
      offline_tag: "1",
      offline_value: "1635063905",
      offline_from: "1635053105",
      offline_to: "1635063905",
    },
    isWishList: "0",
    distance: 3630,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 0,
  },
  {
    restaurant_id: "11",
    rest_name: "Pepper Castle",
    res_description: "North Indian Restaurant",
    min_order_value: "0",
    delivery_handled_by: "2",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "3.4",
    close_time: "23:30",
    open_time: "11:00",
    break_start_time: "",
    break_end_time: "",
    latitude: "1.3107566",
    longitude: "103.7949981",
    del_prep_time: "1hr 0min",
    offline_status: [],
    isWishList: "0",
    distance: 3636,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "14",
    rest_name: "Walker\\'s Bistro",
    res_description: "Indian & Western Cuisine",
    min_order_value: "0",
    delivery_handled_by: "2",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "0",
    close_time: "21:00",
    open_time: "11:30",
    break_start_time: "",
    break_end_time: "",
    latitude: "1.290953",
    longitude: "103.784589",
    del_prep_time: "1hr 0min",
    offline_status: [],
    isWishList: "0",
    distance: 3637,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "17",
    rest_name: "Spice Junction",
    res_description: "Indian Restaurant",
    min_order_value: "10",
    delivery_handled_by: "1",
    time_mode: "2",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "3.2",
    close_time: "23:30",
    open_time: "09:00",
    break_start_time: "",
    break_end_time: "",
    latitude: "1.3096928",
    longitude: "103.8520953",
    del_prep_time: "0hr 30min",
    offline_status: [],
    isWishList: "0",
    distance: 3641,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "10",
    rest_name: "Kaayaloram",
    res_description: "Indian Restaurant",
    min_order_value: "0",
    delivery_handled_by: "2",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "4.4",
    close_time: "19:00",
    open_time: "11:30",
    break_start_time: "",
    break_end_time: "",
    latitude: "1.2882587",
    longitude: "103.8491949",
    del_prep_time: "1hr 0min",
    offline_status: [],
    isWishList: "0",
    distance: 3642,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "55",
    rest_name: "Guest",
    res_description: "Only for testing purpose",
    min_order_value: "0",
    delivery_handled_by: "1",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "4",
    close_time: "23:50",
    open_time: "09:00",
    break_start_time: "11:00",
    break_end_time: "12:00",
    latitude: "1.3342732",
    longitude: "103.9627387",
    del_prep_time: "1hr 25min",
    offline_status: [],
    isWishList: "0",
    distance: 3648,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "9",
    rest_name: "Premaas Cuisine",
    res_description: "Indian Restaurant",
    min_order_value: "0",
    delivery_handled_by: "2",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "4",
    close_time: "11:35",
    open_time: "11:30",
    break_start_time: "",
    break_end_time: "",
    latitude: "1.3050186",
    longitude: "103.8520319",
    del_prep_time: "1hr 15min",
    offline_status: [],
    isWishList: "0",
    distance: 3641,
    restro_is_open: "3",
    next_open_time: "1671593400",
    is_open: 0,
  },
];
export const RestaurentMade = [
  {
    restaurant_id: "73",
    rest_name: "Ibaco",
    res_description: "Tasty and Delicious Ice Creams",
    min_order_value: "0",
    delivery_handled_by: "2",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "0",
    close_time: "22:50",
    open_time: "10:30",
    break_start_time: "18:00",
    break_end_time: "18:30",
    latitude: "12.9653847",
    longitude: "80.246198",
    del_prep_time: "0hr 35min",
    offline_status: [],
    isWishList: "1",
    distance: 1124,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "81",
    rest_name: "lassi corner",
    res_description: "Sweet lasi available here with quality",
    min_order_value: "0",
    delivery_handled_by: "2",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "0",
    close_time: "23:30",
    open_time: "10:30",
    break_start_time: "13:30",
    break_end_time: "14:30",
    latitude: "12.9653847",
    longitude: "80.246198",
    del_prep_time: "0hr 45min",
    offline_status: [],
    isWishList: "0",
    distance: 1124,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "4",
    rest_name: "Paradise Biryani",
    res_description: "Kerala, Indian Restaurant",
    min_order_value: "25",
    delivery_handled_by: "2",
    time_mode: "2",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "3.9",
    close_time: "",
    open_time: "",
    break_start_time: "",
    break_end_time: "",
    latitude: "1.4269313",
    longitude: "103.8260922",
    del_prep_time: "1hr 15min",
    offline_status: {
      offline_tag: "1",
      offline_value: "1635063905",
      offline_from: "1635053105",
      offline_to: "1635063905",
    },
    isWishList: "0",
    distance: 3630,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 0,
  },
  {
    restaurant_id: "11",
    rest_name: "Pepper Castle",
    res_description: "North Indian Restaurant",
    min_order_value: "0",
    delivery_handled_by: "2",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "3.4",
    close_time: "23:30",
    open_time: "11:00",
    break_start_time: "",
    break_end_time: "",
    latitude: "1.3107566",
    longitude: "103.7949981",
    del_prep_time: "1hr 0min",
    offline_status: [],
    isWishList: "0",
    distance: 3636,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "14",
    rest_name: "Walker\\'s Bistro",
    res_description: "Indian & Western Cuisine",
    min_order_value: "0",
    delivery_handled_by: "2",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "0",
    close_time: "21:00",
    open_time: "11:30",
    break_start_time: "",
    break_end_time: "",
    latitude: "1.290953",
    longitude: "103.784589",
    del_prep_time: "1hr 0min",
    offline_status: [],
    isWishList: "0",
    distance: 3637,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "17",
    rest_name: "Spice Junction",
    res_description: "Indian Restaurant",
    min_order_value: "10",
    delivery_handled_by: "1",
    time_mode: "2",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "3.2",
    close_time: "23:30",
    open_time: "09:00",
    break_start_time: "",
    break_end_time: "",
    latitude: "1.3096928",
    longitude: "103.8520953",
    del_prep_time: "0hr 30min",
    offline_status: [],
    isWishList: "0",
    distance: 3641,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "10",
    rest_name: "Kaayaloram",
    res_description: "Indian Restaurant",
    min_order_value: "0",
    delivery_handled_by: "2",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "4.4",
    close_time: "19:00",
    open_time: "11:30",
    break_start_time: "",
    break_end_time: "",
    latitude: "1.2882587",
    longitude: "103.8491949",
    del_prep_time: "1hr 0min",
    offline_status: [],
    isWishList: "0",
    distance: 3642,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "55",
    rest_name: "Guest",
    res_description: "Only for testing purpose",
    min_order_value: "0",
    delivery_handled_by: "1",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "4",
    close_time: "23:50",
    open_time: "09:00",
    break_start_time: "11:00",
    break_end_time: "12:00",
    latitude: "1.3342732",
    longitude: "103.9627387",
    del_prep_time: "1hr 25min",
    offline_status: [],
    isWishList: "0",
    distance: 3648,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "9",
    rest_name: "Premaas Cuisine",
    res_description: "Indian Restaurant",
    min_order_value: "0",
    delivery_handled_by: "2",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "4",
    close_time: "11:35",
    open_time: "11:30",
    break_start_time: "",
    break_end_time: "",
    latitude: "1.3050186",
    longitude: "103.8520319",
    del_prep_time: "1hr 15min",
    offline_status: [],
    isWishList: "0",
    distance: 3641,
    restro_is_open: "3",
    next_open_time: "1671593400",
    is_open: 0,
  },
];
export const HomeMade = [
  {
    restaurant_id: "36",
    rest_name: "My Singapore Kitchen",
    res_description: "HOMEMADE CUISINE, Food for all reasons",
    min_order_value: "0",
    delivery_handled_by: "2",
    time_mode: "2",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "5",
    close_time: "20:00",
    open_time: "10:00",
    break_start_time: "",
    break_end_time: "",
    latitude: "1.3338678",
    longitude: "103.7211787",
    del_prep_time: "1hr 0min",
    offline_status: [],
    isWishList: "0",
    distance: 3628,
    restro_is_open: "3",
    next_open_time: "1672106400",
    is_open: 0,
  },
];

export const Grocery = [
  {
    restaurant_id: "97",
    rest_name: "Kadhir Super Store",
    res_description: "test",
    min_order_value: "0",
    delivery_handled_by: "1",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "0",
    close_time: "",
    open_time: "",
    break_start_time: "",
    break_end_time: "",
    latitude: "11.0170548",
    longitude: "76.9620648",
    del_prep_time: "0hr 0min",
    offline_status: [],
    isWishList: "0",
    distance: 1336,
    restro_is_open: "3",
    next_open_time: "86400",
    is_open: 0,
  },
];

export const BeveragesItems = [
  {
    restaurant_id: "31",
    rest_name: "Instant Alcohol Delivery",
    res_description: "Alcohol delivery in 60 minutes from 10 AM to 1:30 AM",
    min_order_value: "0",
    delivery_handled_by: "1",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "3",
    close_time: "23:59",
    open_time: "00:00",
    break_start_time: "01:30",
    break_end_time: "10:00",
    latitude: "1.3081446",
    longitude: "103.8530341",
    del_prep_time: "0hr 0min",
    offline_status: [],
    isWishList: "0",
    distance: 3641,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "38",
    rest_name: "DRINQ",
    res_description: "One hour Alcohol delivery",
    min_order_value: "0",
    delivery_handled_by: "1",
    time_mode: "2",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "0",
    close_time: "23:59",
    open_time: "00:00",
    break_start_time: "03:00",
    break_end_time: "19:00",
    latitude: "1.3513714",
    longitude: "103.8430959",
    del_prep_time: "1hr 5min",
    offline_status: [],
    isWishList: "0",
    distance: 3637,
    restro_is_open: "2",
    next_open_time: "1671620400",
    is_open: 0,
  },
];

export const Dinein = [
  {
    restaurant_id: "73",
    rest_name: "Ibaco",
    res_description: "Tasty and Delicious Ice Creams",
    min_order_value: "0",
    delivery_handled_by: "2",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "0",
    close_time: "22:50",
    open_time: "10:30",
    break_start_time: "18:00",
    break_end_time: "18:30",
    latitude: "12.9653847",
    longitude: "80.246198",
    del_prep_time: "0hr 35min",
    offline_status: [],
    isWishList: "0",
    distance: 1124,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "81",
    rest_name: "lassi corner",
    res_description: "Sweet lasi available here with quality",
    min_order_value: "0",
    delivery_handled_by: "2",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "0",
    close_time: "23:30",
    open_time: "10:30",
    break_start_time: "13:30",
    break_end_time: "14:30",
    latitude: "12.9653847",
    longitude: "80.246198",
    del_prep_time: "0hr 45min",
    offline_status: [],
    isWishList: "0",
    distance: 1124,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "11",
    rest_name: "Pepper Castle",
    res_description: "North Indian Restaurant",
    min_order_value: "0",
    delivery_handled_by: "2",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "3.4",
    close_time: "23:30",
    open_time: "11:00",
    break_start_time: "",
    break_end_time: "",
    latitude: "1.3107566",
    longitude: "103.7949981",
    del_prep_time: "1hr 0min",
    offline_status: [],
    isWishList: "0",
    distance: 3636,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "17",
    rest_name: "Spice Junction",
    res_description: "Indian Restaurant",
    min_order_value: "10",
    delivery_handled_by: "1",
    time_mode: "2",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "3.2",
    close_time: "23:30",
    open_time: "09:00",
    break_start_time: "",
    break_end_time: "",
    latitude: "1.3096928",
    longitude: "103.8520953",
    del_prep_time: "0hr 30min",
    offline_status: [],
    isWishList: "0",
    distance: 3641,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
  {
    restaurant_id: "55",
    rest_name: "Guest",
    res_description: "Only for testing purpose",
    min_order_value: "0",
    delivery_handled_by: "1",
    time_mode: "1",
    rest_status: "1",
    banner_image:
      "https://keralaeats.appplaza.io/assets/images/default_restaurant_banner.jpg",
    avg_rating: "4",
    close_time: "23:50",
    open_time: "09:00",
    break_start_time: "11:00",
    break_end_time: "12:00",
    latitude: "1.3342732",
    longitude: "103.9627387",
    del_prep_time: "1hr 25min",
    offline_status: [],
    isWishList: "0",
    distance: 3648,
    restro_is_open: "1",
    next_open_time: "",
    is_open: 1,
  },
];

export const ProductListing = 
{
  restaurant_id: "8",
  rest_name: "Marmaris",
  res_description: "Kerala & Arabian Restaurant",
  min_order_value: "0",
  delivery_handled_by: "2",
  time_mode: "2",
  rest_status: "1",
  banner_image: "https://keralaeats.appplaza.io/assets/merchant/merchant_banner_image/210833271625119979210701_banner_image.jpg",
  avg_rating: "3.4",
  close_time: "22:00",
  open_time: "11:30",
  break_start_time: "",
  break_end_time: "",
  latitude: "1.3055374",
  longitude: "103.8528944",
  del_prep_time: "1hr 10min",
  offline_status: {
      offline_tag: "2",
      offline_value: "1664208000",
      offline_from: "1664208000",
      offline_to: "1664294400"
  },
  isWishList: "0",
  restro_is_open: "1",
  next_open_time: "",
  category_list: [
      {
          category_id: "968",
          category_name: "Arabian Delights",
          product_list: [
              {
                  product_id: "6888",
                  product_name: "Chicken Kabsa- 1pax",
                  min_qty: "0",
                  product_position_order: "0",
                  product_description: "A fragrant Rice cooked in meat broth simmered in spices and tomatoes served with chicken",
                  price: "19.90",
                  offer_price: "0.00",
                  product_image: "https://keralaeats.appplaza.io/assets/merchant/merchant_banner_image/210941411625120738210701_banner_image.jpg",
                  is_product_veg: "2",
                  off_id: null,
                  rest_id: null,
                  category_id: null,
                offline_tag: null,
                  offline_value: null,
                  offline_from: null,
                  offline_to: null,
                  is_product_avl: 1,
                  isCart: 0,
                  cart: [],
                  is_variant_avl: 0
              },
              {
                  product_id: "6889",
                  product_name: "Chicken Kabsa- 2pax",
                  min_qty: "0",
                  product_position_order: "0",
                  product_description: "A fragrant Rice cooked in meat broth simmered in spices and tomatoes served with chicken",
                  price: "37.90",
                  offer_price: "0.00",
                  product_image: "",
                  is_product_veg: "2",
                  off_id: null,
                  rest_id: null,
                  category_id: null,
                  offline_tag: null,
                  offline_value: null,
                  offline_from: null,
                  offline_to: null,
                  is_product_avl: 1,
                  isCart: 0,
                  cart: [],
                  is_variant_avl: 0
              },
              {
                  product_id: "6890",
                  product_name: "Chicken Kabsa- 4pax",
                  min_qty: "0",
                  product_position_order: "0",
                  product_description: "A fragrant Rice cooked in meat broth simmered in spices and tomatoes served with chicken",
                  price: "71.90",
                  offer_price: "0.00",
                  product_image: "",
                  is_product_veg: "2",
                off_id: null,
                  rest_id: null,
                  category_id: null,
                  offline_tag: null,
                  offline_value: null,
                  offline_from: null,
                  offline_to: null,
                  is_product_avl: 1,
                  isCart: 0,
                  cart: [],
                  is_variant_avl: 0
              },
              {
                  product_id: "6876",
                  product_name: "Chicken Mandi- 1pax",
                  min_qty: "0",
                  product_position_order: "0",
                  product_description: "Served with Salad and Spcl Mandi Sauce",
                  price: "18.90",
                  offer_price: "0.00",
                  product_image: "",
                  is_product_veg: "2",
                  off_id: null,
                  rest_id: null,
                  category_id: null,
                  offline_tag: null,
                  offline_value: null,
                  offline_from: null,
                  offline_to: null,
                  is_product_avl: 1,
              isCart: 0,
                  cart: [],
                  is_variant_avl: 0
              },
              {
                  product_id: "6877",
                  product_name: "Chicken Mandi- 2pax",
                  min_qty: "0",
                  product_position_order: "0",
                  product_description: "Served with Salad and Spcl Mandi Sauce",
                  price: "35.90",
                  offer_price: "0.00",
                  product_image: "",
                  is_product_veg: "2",
                  off_id: null,
                  rest_id: null,
                  category_id: null,
                  offline_tag: null,
                  offline_value: null,
                  offline_from: null,
                  offline_to: null,
                  is_product_avl: 1,
                  isCart: 0,
                  cart: [],
                  is_variant_avl: 0
              },
              {
                  product_id: "6878",
                  product_name: "Chicken Mandi- 4pax",
                  min_qty: "0",
                  product_position_order: "0",
                product_description: "Served with Salad and Spcl Mandi Sauce",
                  price: "67.90",
                  offer_price: "0.00",
                  product_image: "",
                  is_product_veg: "2",
                  off_id: null,
                  rest_id: null,
                  category_id: null,
                offline_tag: null,
                 offline_value: null,
                offline_from: null,
                 offline_to: null,
                  is_product_avl: 1,
                  isCart: 0,
                  cart: [],
                  is_variant_avl: 0
              },
              {
                  product_id: "6885",
                  product_name: "Fish Mandi 1 Pax (Batang Fish)",
                  min_qty: "0",
                  product_position_order: "0",
                  product_description: "Served with Salad and Spcl Mandi Sauce",
                  price: "18.90",
                  offer_price: "0.00",
                  product_image: "",
                  is_product_veg: "2",
                  off_id: null,
                  rest_id: null,
                  category_id: null,
                offline_tag: null,
                 offline_value: null,
                offline_from: null,
                 offline_to: null,
                  is_product_avl: 1,
                  isCart: 0,
                  cart: [],
                  is_variant_avl: 0
              }
           
          ]
      },
      {
        category_id: "973",
        category_name: "Juice, Shakes and Cold Drinks",
        product_list: [
            {
                product_id: "6926",
                product_name: "Avacado Milk Shake",
                min_qty: "0",
                product_position_order: "0",
                product_description: "",
                price: "6.80",
                offer_price: "0.00",
                product_image: "",
                is_product_veg: "1",
                off_id: null,
                rest_id: null,
                category_id: null,
              offline_tag: null,
                offline_value: null,
                offline_from: null,
                offline_to: null,
                is_product_avl: 1,
                isCart: 0,
                cart: [],
                is_variant_avl: 0
            },
            {
                product_id: "6928",
                product_name: "Fresh Lime Juice (Salt/Sweet)",
                min_qty: "0",
                product_position_order: "0",
                product_description: "",
                price: "3.90",
                offer_price: "0.00",
                product_image: "",
                is_product_veg: "1",
                off_id: null,
              rest_id: null,
                category_id: null,
                offline_tag: null,
              offline_value: null,
              offline_from: null,
                offline_to: null,
                is_product_avl: 1,
                isCart: 0,
                cart: [],
              is_variant_avl: 0
            },
            {
                product_id: "6929",
                product_name: "Fresh Lime Mint Juice",
                min_qty: "0",
                product_position_order: "0",
                product_description: "",
                price: "4.90",
                offer_price: "0.00",
                product_image: "",
                is_product_veg: "1",
                off_id: null,
                rest_id: null,
                category_id: null,
              offline_tag: null,
              offline_value: null,
                offline_from: null,
                offline_to: null,
                is_product_avl: 1,
                isCart: 0,
                car: [],
                is_variant_avl: 0
            },
            {
                product_id: "2579",
                product_name: "Fresh Lime Soda",
                min_qty: "0",
                product_position_order: "0",
                product_description: "",
                price: "5.50",
                offer_price: "0.00",
                product_image: "",
                is_product_veg: "1",
                off_id: null,
                rest_id: null,
              category_id: null,
               offline_tag: null,
                offline_value: null,
                offline_from: null,
                offline_to: null,
                is_product_avl: 1,
                isCart: 0,
                cart: [],
                is_variant_avl: 0
            },
          ]},
          {
            category_id: "2168",
            category_name: "Marmaris Sensations",
            product_list: [
                {
                    product_id: "13140",
                    product_name: "Al Faham (Black Pepper) - Half",
                    min_qty: "0",
                    product_position_order: "0",
                  product_description: "Charcoal Grilled Chicken Served with 1 Pitta bread, Veg salad and garlic sauce)",
                    price: "21.90",
                    offer_price: "0.00",
                    product_image: "assets/images/products/resized_product_pic/221499831670579280221209.jpg",
                    is_product_veg: "2",
                    off_id: null,
                  rest_id: null,
                    category_id: null,
                    offline_tag: null,
                    offline_value: null,
                    offline_from: null,
                    offline_to: null,
                  is_product_avl: 1,
                    isCart: 0,
                    cart: [],
                    is_variant_avl: 0
                },
                {
                    product_id: "13141",
                  product_name: "Al Faham (Black Pepper) Full",
                  min_qty: "0",
                    product_position_order: "0",
                    product_description: "Charcoal Grilled Chicken  Served with 2 Pitta bread, Veg salad and garlic sauce",
                    price: "41.90",
                  offer_price: "0.00",
                    product_image: "",
                    is_product_veg: "2",
                    off_id: null,
                  rest_id: null,
                    category_id: null,
                    offline_tag: null,
                    offline_value: null,
                    offline_from: null,
                    offline_to: null,
                    is_product_avl: 1,
                  isCart: 0,
                    cart: [],
                    is_variant_avl: 0
                },
              ]
        },
        {
            category_id: "965",
            category_name: "Salads & Soups",
            product_list: [
                {
                    product_id: "6864",
                  product_name: "Arabic Salad",
                    min_qty: "0",
                    product_position_order: "0",
                    product_description: "Shibth (Dill Leaf), greens, red cabbage, carrot, coriender & mint leaves with olives, pomegranate and dressed with olive oil.",
                    price: "12.90",
                    offer_price: "0.00",
                    product_image: "",
                    is_product_veg: "1",
                    off_id: null,
                    rest_id: null,
                    category_id: null,
                    offline_tag: null,
                    offline_value: null,
                    offline_from: null,
                    offline_to: null,
                    is_product_avl: 1,
                    isCart: 0,
                    cart: [],
                    is_variant_avl: 0
                },
                {
                    product_id: "6860",
                  product_name: "Clear Mushroom Soup",
                   min_qty: "0",
                    product_position_order: "0",
                    product_description: "Mushroms, Greens, lemongrass slow cooked in mild pepper spices",
                    price: "7.80",
                    offer_price: "0.00",
                  product_image: "",
                    is_product_veg: "1",
                    off_id: null,
                    rest_id: null,
                    category_id: null,
                    offline_tag: null,
                    offline_value: null,
                    offline_from: null,
                  offline_to: null,
                    is_product_avl: 1,
                    isCart: 0,
                    cart: [],
                    is_variant_avl: 0
                },
                {
                    product_id: "6859",
                    product_name: "Clear Vegetable Soup",
                    min_qty: "0",
                    product_position_order: "0",
                    product_description: "Carrots, Greens, sliced beans slow cooked in mild pepper spices",
                    price: "6.80",
                    offer_price: "0.00",
                    product_image: "https://keralaeats.appplaza.io/assets/merchant/merchant_banner_image/210941411625120738210701_banner_image.jpg",
                    is_product_veg: "1",
                    off_id: null,
                    rest_id: null,
                    category_id: null,
                    offline_tag: null,
                    offline_value: null,
                    offline_from: null,
                    offline_to: null,
                    is_product_avl: 1,
                    isCart: 0,
                    cart: [],
                    is_variant_avl: 0
                },
                {
                    product_id: "6863",
                    product_name: "Cream Chicken Soup",
                    min_qty: "0",
                    product_position_order: "0",
                    product_description: "Chicken cooked in mild spices and herbs with added cream",
                    price: "7.80",
                    offer_price: "0.00",
                  product_image: "",
                    is_product_veg: "2",
                    off_id: null,
                    rest_id: null,
                    category_id: null,
                    offline_tag: null,
                    offline_value: null,
                    offline_from: null,
                    offline_to: null,
                    is_product_avl: 1,
                    isCart: 0,
                    cart: [],
                    is_variant_avl: 0
                },
                {
                    product_id: "6861",
                    product_name: "Cream Mushroom Soup",
                    min_qty: "0",
                    product_position_order: "0",
                    product_description: "Mushroms, Greens, lemongrass slow cooked in mild pepper spices with added cream",
                    price: "7.80",
                    offer_price: "0.00",
                    product_image: "",
                  is_product_veg: "1",
                    off_id: null,
                    rest_id: null,
                    category_id: null,
                  offline_tag: null,
                    offline_value: null,
                    offline_from: null,
                    offline_to: null,
                    is_product_avl: 1,
                    isCart: 0,
                    cart: [],
                    is_variant_avl: 0
                },
              ]},
              {
                category_id: "967",
                category_name: "Shawarma and Platters ( Available 1.00pm Onwards)",
                product_list: [
                    {
                        product_id: "6870",
                        product_name: "Chicken shawarma in Arabic bread(Available after 1 Pm)",
                        min_qty: "0",
                        product_position_order: "6",
                        product_description: "Prepared with Tahini, Garlic, Mayonnaise and Hot Sauce",
                        price: "8.90",
                        offer_price: "0.00",
                        product_image: "",
                        is_product_veg: "2",
                        off_id: null,
                        rest_id: null,
                        category_id: null,
                        offline_tag: null,
                        offline_value: null,
                        offline_from: null,
                        offline_to: null,
                        is_product_avl: 1,
                        isCart: 0,
                        cart: [],
                        is_variant_avl: 1
                    },
                    {
                        product_id: "6871",
                        product_name: "Chicken shawarma in long bun",
                        min_qty: "0",
                        product_position_order: "5",
                        product_description: "Prepared with Tahini, Garlic, Mayonnaise and Hot Sauce",
                        price: "8.90",
                        offer_price: "0.00",
                        product_image: "",
                        is_product_veg: "2",
                        off_id: null,
                        rest_id: null,
                        category_id: null,
                        offline_tag: null,
                        offline_value: null,
                        offline_from: null,
                        offline_to: null,
                        is_product_avl: 1,
                        isCart: 0,
                        cart: [],
                        is_variant_avl: 1
                    },
                    {
                        product_id: "6872",
                        product_name: "Mexican Shawarma in arabic bread",
                        min_qty: "0",
                        product_position_order: "4",
                        product_description: "Prepared with Tahini, Garlic, Mayonnaise and Hot Sauce",
                        price: "9.90",
                        offer_price: "0.00",
                        product_image: "",
                        is_product_veg: "2",
                        off_id: null,
                        rest_id: null,
                        category_id: null,
                      offline_tag: null,
                        offline_value: null,
                        offline_from: null,
                        offline_to: null,
                      is_product_avl: 1,
                        isCart: 0,
                        cart: [],
                        is_variant_avl: 1
                    },
                    {
                        product_id: "6873",
                        product_name: "Mexican shawarma in long bun ",
                    min_qty: "0",
                        product_position_order: "3",
                        product_description: "Prepared with Tahini, Garlic, Mayonnaise and Hot Sauce",
                        price: "9.90",
                        offer_price: "0.00",
                        product_image: "",
                      is_product_veg: "2",
                       off_id: null,
                        rest_id: null,
                        category_id: null,
                        offline_tag: null,
                        offline_value: null,
                        offline_from: null,
                        offline_to: null,
                        is_product_avl: 1,
                        isCart: 0,
                        cart: [],
                        is_variant_avl: 1
                    },]},
                    {
                      category_id: "969",
                      category_name: "Singnature & Grills",
                      product_list: [
                          {
                              product_id: "6902",
                              product_name: "Al Faham (Grilled Chicken Full)* Slow Grilled with Special Spices in perfection)",
                              min_qty: "0",
                              product_position_order: "2",
                            product_description: "Served with garlic sauce, veg salad and 2 Pitta breads",
                              price: "37.90",
                              offer_price: "0.00",
                              product_image: "",
                              is_product_veg: "2",
                              off_id: null,
                            rest_id: null,
                             category_id: null,
                              offline_tag: null,
                            offline_value: null,
                              offline_from: null,
                              offline_to: null,
                              is_product_avl: 1,
                              isCart: 0,
                              cart: [],
                            is_variant_avl: 1
                          },
                          {
                              "product_id": "6901",
                              "product_name": "Al Faham (Grilled Chicken half)* Slow Grilled with Special Spices in perfection)",
                              "min_qty": "0",
                              "product_position_order": "1",
                              "product_description": "Served with garlic sauce, veg salad and 1 Pitta bread",
                              "price": "19.90",
                              "offer_price": "0.00",
                              "product_image": "",
                              "is_product_veg": "2",
                              "off_id": null,
                              "rest_id": null,
                              "category_id": null,
                              "offline_tag": null,
                              "offline_value": null,
                              "offline_from": null,
                              "offline_to": null,
                              "is_product_avl": 1,
                              "isCart": 0,
                              "cart": [],
                              "is_variant_avl": 1
                          },
                          {
                              "product_id": "6903",
                              "product_name": "Al Faham (Grilled Chicken Quater) with Hummus (Small Portion)",
                              "min_qty": "0",
                              "product_position_order": "3",
                              "product_description": "Served with garlic sauce, veg salad and 1 Pitta bread",
                              "price": "16.90",
                              "offer_price": "0.00",
                              "product_image": "",
                              "is_product_veg": "2",
                              "off_id": null,
                              "rest_id": null,
                              "category_id": null,
                              "offline_tag": null,
                              "offline_value": null,
                              "offline_from": null,
                              "offline_to": null,
                              "is_product_avl": 1,
                              "isCart": 0,
                              "cart": [],
                              "is_variant_avl": 1
                          },
                          {
                              "product_id": "6904",
                              "product_name": "Al Faham (Grilled Chicken Quater) with Muthabbal (Small Portion)",
                              "min_qty": "0",
                              "product_position_order": "4",
                              "product_description": "Served with garlic sauce, veg salad and 1 Pitta bread",
                              "price": "17.90",
                              "offer_price": "0.00",
                              "product_image": "",
                              "is_product_veg": "2",
                              "off_id": null,
                              "rest_id": null,
                              "category_id": null,
                              "offline_tag": null,
                              "offline_value": null,
                              "offline_from": null,
                              "offline_to": null,
                              "is_product_avl": 1,
                              "isCart": 0,
                              "cart": [],
                              "is_variant_avl": 1
                          },]},
                          {
                            category_id: "971",
                            category_name: "Western",
                            product_list: [
                               {
                                    product_id: "2548",
                                    product_name: "Beef Burger Meal (With Cheese)",
                                    min_qty: "0",
                                    product_position_order: "0",
                                    product_description: "Served with Small fries, Ketchup, Chilli Sauce and Choice of Soft Drink",
                                    price: "7.90",
                                    offer_price: "0.00",
                                    product_image: "",
                                    is_product_veg: "2",
                                  off_id: null,
                                   rest_id: null,
                                    category_id: null,
                                    offline_tag: null,
                                    offline_value: null,
                                    offline_from: null,
                                    offline_to: null,
                                    is_product_avl: 1,
                                    isCart: 0,
                                    cart: [],
                                    is_variant_avl: 0
                                },
                                {
                                    product_id: "2547",
                                    product_name: "Beef Burger with Cheese",
                                    min_qty: "0",
                                    product_position_order: "0",
                                    product_description: "Served with Ketchup and Chilli Sauce",
                                    price: "5.50",
                                    offer_price: "0.00",
                                    product_image: "",
                                    is_product_veg: "2",
                                    off_id: null,
                                    rest_id: null,
                                    category_id: null,
                                    offline_tag: null,
                                    offline_value: null,
                                    offline_from: null,
                                    offline_to: null,
                                    is_product_avl: 1,
                                    isCart: 0,
                                    cart: [],
                                    is_variant_avl: 0
                                },
                                {
                                    product_id: "6921",
                                    product_name: "Cheese Fries",
                                    min_qty: "0",
                                    product_position_order: "0",
                                    product_description: "Served with Nacho Cheese, Ketchup and Chilli Sauce",
                                    price: "6.90",
                                    offer_price: "0.00",
                                    product_image: "",
                                    is_product_veg: "1",
                                    off_id: null,
                                    rest_id: null,
                                    category_id: null,
                                    offline_tag: null,
                                    offline_value: null,
                                  offline_from: null,
                                    offline_to: null,
                                    is_product_avl: 1,
                                    isCart: 0,
                                    cart: [],
                                    is_variant_avl: 0
                                },
                                {
                                    product_id : "2546",
                                    product_name: "Chicken Burger Meal (With Cheese)",
                                  min_qty: "0",
                                    product_position_order: "0",
                                    product_description: "Served with Small fries, Ketchup, Chilli Sauce and Choice of Soft Drink",
                                    price: "7.90",
                                    offer_price: "0.00",
                                    product_image: "",
                                  is_product_veg: "2",
                                   off_id: null,
                                    rest_id: null,
                                    category_id: null,
                                    offline_tag: null,
                                    offline_value: null,
                                  offline_from: null,
                                    offline_to: null,
                                    is_product_avl: 1,
                                    isCart: 0,
                                    cart: [],
                                    is_variant_avl: 0
                                },]},
                                {
                                  category_id: "971",
                                  category_name: "Western",
                                  product_list: [
                                     {
                                          product_id: "2548",
                                          product_name: "Beef Burger Meal (With Cheese)",
                                          min_qty: "0",
                                          product_position_order: "0",
                                          product_description: "Served with Small fries, Ketchup, Chilli Sauce and Choice of Soft Drink",
                                          price: "7.90",
                                          offer_price: "0.00",
                                          product_image: "",
                                          is_product_veg: "2",
                                        off_id: null,
                                         rest_id: null,
                                          category_id: null,
                                          offline_tag: null,
                                          offline_value: null,
                                          offline_from: null,
                                          offline_to: null,
                                          is_product_avl: 1,
                                          isCart: 0,
                                          cart: [],
                                          is_variant_avl: 0
                                      },
                                      {
                                          product_id: "2547",
                                          product_name: "Beef Burger with Cheese",
                                          min_qty: "0",
                                          product_position_order: "0",
                                          product_description: "Served with Ketchup and Chilli Sauce",
                                          price: "5.50",
                                          offer_price: "0.00",
                                          product_image: "",
                                          is_product_veg: "2",
                                          off_id: null,
                                          rest_id: null,
                                          category_id: null,
                                          offline_tag: null,
                                          offline_value: null,
                                          offline_from: null,
                                          offline_to: null,
                                          is_product_avl: 1,
                                          isCart: 0,
                                          cart: [],
                                          is_variant_avl: 0
                                      },
                                      {
                                          product_id: "6921",
                                          product_name: "Cheese Fries",
                                          min_qty: "0",
                                          product_position_order: "0",
                                          product_description: "Served with Nacho Cheese, Ketchup and Chilli Sauce",
                                          price: "6.90",
                                          offer_price: "0.00",
                                          product_image: "",
                                          is_product_veg: "1",
                                          off_id: null,
                                          rest_id: null,
                                          category_id: null,
                                          offline_tag: null,
                                          offline_value: null,
                                        offline_from: null,
                                          offline_to: null,
                                          is_product_avl: 1,
                                          isCart: 0,
                                          cart: [],
                                          is_variant_avl: 0
                                      },
                                      {
                                          product_id : "2546",
                                          product_name: "Chicken Burger Meal (With Cheese)",
                                        min_qty: "0",
                                          product_position_order: "0",
                                          product_description: "Served with Small fries, Ketchup, Chilli Sauce and Choice of Soft Drink",
                                          price: "7.90",
                                          offer_price: "0.00",
                                          product_image: "",
                                        is_product_veg: "2",
                                         off_id: null,
                                          rest_id: null,
                                          category_id: null,
                                          offline_tag: null,
                                          offline_value: null,
                                        offline_from: null,
                                          offline_to: null,
                                          is_product_avl: 1,
                                          isCart: 0,
                                          cart: [],
                                          is_variant_avl: 0
                                      },]},
                                      {
                                        category_id: "971",
                                        category_name: "Western",
                                        product_list: [
                                           {
                                                product_id: "2548",
                                                product_name: "Beef Burger Meal (With Cheese)",
                                                min_qty: "0",
                                                product_position_order: "0",
                                                product_description: "Served with Small fries, Ketchup, Chilli Sauce and Choice of Soft Drink",
                                                price: "7.90",
                                                offer_price: "0.00",
                                                product_image: "",
                                                is_product_veg: "2",
                                              off_id: null,
                                               rest_id: null,
                                                category_id: null,
                                                offline_tag: null,
                                                offline_value: null,
                                                offline_from: null,
                                                offline_to: null,
                                                is_product_avl: 1,
                                                isCart: 0,
                                                cart: [],
                                                is_variant_avl: 0
                                            },
                                            {
                                                product_id: "2547",
                                                product_name: "Beef Burger with Cheese",
                                                min_qty: "0",
                                                product_position_order: "0",
                                                product_description: "Served with Ketchup and Chilli Sauce",
                                                price: "5.50",
                                                offer_price: "0.00",
                                                product_image: "",
                                                is_product_veg: "2",
                                                off_id: null,
                                                rest_id: null,
                                                category_id: null,
                                                offline_tag: null,
                                                offline_value: null,
                                                offline_from: null,
                                                offline_to: null,
                                                is_product_avl: 1,
                                                isCart: 0,
                                                cart: [],
                                                is_variant_avl: 0
                                            },
                                            {
                                                product_id: "6921",
                                                product_name: "Cheese Fries",
                                                min_qty: "0",
                                                product_position_order: "0",
                                                product_description: "Served with Nacho Cheese, Ketchup and Chilli Sauce",
                                                price: "6.90",
                                                offer_price: "0.00",
                                                product_image: "",
                                                is_product_veg: "1",
                                                off_id: null,
                                                rest_id: null,
                                                category_id: null,
                                                offline_tag: null,
                                                offline_value: null,
                                              offline_from: null,
                                                offline_to: null,
                                                is_product_avl: 1,
                                                isCart: 0,
                                                cart: [],
                                                is_variant_avl: 0
                                            },
                                            {
                                                product_id : "2546",
                                                product_name: "Chicken Burger Meal (With Cheese)",
                                              min_qty: "0",
                                                product_position_order: "0",
                                                product_description: "Served with Small fries, Ketchup, Chilli Sauce and Choice of Soft Drink",
                                                price: "7.90",
                                                offer_price: "0.00",
                                                product_image: "",
                                              is_product_veg: "2",
                                               off_id: null,
                                                rest_id: null,
                                                category_id: null,
                                                offline_tag: null,
                                                offline_value: null,
                                              offline_from: null,
                                                offline_to: null,
                                                is_product_avl: 1,
                                                isCart: 0,
                                                cart: [],
                                                is_variant_avl: 0
                                            },]},

    ]}
    
export const AddressVals = {
  lat: "75.00003",
  lng: "62.0215487",
  pin_address: "New MGR Road",
  unit_number: "5th main road",
  street_address: "New way",
  postal_code: "600096",
};
